### ISSUE TITLE
Hacktober Challenge

### ISSUE THREAD

**Issue by rehanvipin** [rehanvipin/styx#16]
Make the files-being-hosted page. This can be done through HTML, CSS, Bootstrap, JQuery or any other web development tool you are comfortable with. None of the buttons need to be functinoal, just a static page for now.
Conform to the wireframe/wireframe.pdf for guidelines on how the site should look.

**Comment by RookTKO** [comment]
Just forked it. I'll see what I can do!

**Comment by RookTKO** [comment]
I just created a pull request. Let me know what you think!
