### ISSUE TITLE
Front-end work

### ISSUE THREAD

**Issue by rehanvipin** [rehanvipin/styx#5]
Work needed to be done on the project:
* Make the login page look like the wire-frame. Need to setup it up with the back-end.
* Add simple validation to the login page with javascript or jquery.
* Add the data to the home page's main display, need to integrate jquery into it.
* Make a simple draft of the messaging-chat server, maybe with javascript ( was thinking of using python)

**Comment by RookTKO** [comment]
I can get to this later today if you guys still need this done.

**Comment by RookTKO** [comment]
Can break up all the bullets into separate bullets. I understand it's front end work but I won't get to all of it in one night.

**Comment by RookTKO** [comment]
Added HTML form validation. Don't have time to fix the PHP form validation today. I will work on it this weekend.

**Comment by RookTKO** [comment]
I got swamped. I will be trying to do some of the PHP form validation this weekend.
